-- Ads Autopilot AI Advanced Automation Migration
-- Version: 004 - Enterprise Advanced Automation System
-- Description: Tables for Enterprise-tier AI automation and bid management

-- Automation Rules Table
-- Stores custom automation rules and configurations
CREATE TABLE IF NOT EXISTS automation_rules (
  id SERIAL PRIMARY KEY,
  tenant_id VARCHAR(100) NOT NULL,
  rule_name VARCHAR(200) NOT NULL,
  automation_type VARCHAR(50) NOT NULL, -- 'bid_optimization', 'budget_allocation', 'keyword_expansion', etc.
  rule_config JSONB NOT NULL, -- Algorithm-specific configuration
  trigger_conditions JSONB NOT NULL, -- When to trigger the automation
  action_config JSONB NOT NULL, -- What actions to take
  schedule_config JSONB DEFAULT '{}', -- When to run (cron-like scheduling)
  is_active BOOLEAN DEFAULT true,
  priority INTEGER DEFAULT 5, -- 1 (highest) to 10 (lowest)
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  last_executed_at TIMESTAMP WITH TIME ZONE,
  execution_count INTEGER DEFAULT 0,
  
  UNIQUE(tenant_id, rule_name)
);

-- Custom Bid Strategies Table
-- Enterprise-specific custom bidding algorithms
CREATE TABLE IF NOT EXISTS custom_bid_strategies (
  id SERIAL PRIMARY KEY,
  tenant_id VARCHAR(100) NOT NULL,
  strategy_name VARCHAR(200) NOT NULL,
  strategy_description TEXT,
  algorithm_config JSONB NOT NULL, -- Custom algorithm parameters
  performance_targets JSONB NOT NULL, -- Target CPA, ROAS, CTR, etc.
  constraints JSONB DEFAULT '{}', -- Min/max bid limits, budget constraints
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  last_used_at TIMESTAMP WITH TIME ZONE,
  usage_count INTEGER DEFAULT 0,
  average_performance JSONB DEFAULT '{}', -- Historical performance metrics
  
  UNIQUE(tenant_id, strategy_name)
);

-- Automation Execution Logs Table
-- Track all automation executions and results
CREATE TABLE IF NOT EXISTS automation_execution_logs (
  id SERIAL PRIMARY KEY,
  tenant_id VARCHAR(100) NOT NULL,
  automation_id VARCHAR(100) NOT NULL, -- Can be rule_id, strategy_id, or 'suite'
  automation_type VARCHAR(50) NOT NULL,
  activity_type VARCHAR(50) NOT NULL, -- 'executed', 'failed', 'created', 'modified'
  execution_status VARCHAR(20) DEFAULT 'pending', -- 'pending', 'running', 'completed', 'failed'
  metadata JSONB DEFAULT '{}', -- Execution details, results, errors
  execution_duration INTEGER, -- Milliseconds
  executed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  completed_at TIMESTAMP WITH TIME ZONE,
  
  INDEX (tenant_id, executed_at),
  INDEX (automation_id, executed_at),
  INDEX (automation_type, executed_at)
);

-- Bid Adjustment History Table
-- Track all automated bid changes for audit and rollback
CREATE TABLE IF NOT EXISTS bid_adjustment_history (
  id SERIAL PRIMARY KEY,
  tenant_id VARCHAR(100) NOT NULL,
  campaign_id VARCHAR(100) NOT NULL,
  ad_group_id VARCHAR(100),
  keyword_id VARCHAR(100),
  adjustment_type VARCHAR(30) NOT NULL, -- 'bid_multiplier', 'bid_amount', 'budget_change'
  old_value DECIMAL(10,2),
  new_value DECIMAL(10,2),
  adjustment_reason TEXT,
  automation_rule_id INTEGER REFERENCES automation_rules(id),
  bid_strategy_id INTEGER REFERENCES custom_bid_strategies(id),
  performance_data JSONB DEFAULT '{}', -- Performance metrics at time of change
  estimated_impact JSONB DEFAULT '{}', -- Predicted impact of the change
  actual_impact JSONB DEFAULT '{}', -- Measured impact after change (populated later)
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  measured_at TIMESTAMP WITH TIME ZONE -- When actual impact was measured
);

-- Automation Performance Metrics Table
-- Track the effectiveness of different automation strategies
CREATE TABLE IF NOT EXISTS automation_performance_metrics (
  id SERIAL PRIMARY KEY,
  tenant_id VARCHAR(100) NOT NULL,
  automation_type VARCHAR(50) NOT NULL,
  automation_id INTEGER, -- References automation_rules.id or custom_bid_strategies.id
  metric_date DATE NOT NULL,
  campaigns_optimized INTEGER DEFAULT 0,
  total_adjustments INTEGER DEFAULT 0,
  cost_savings DECIMAL(10,2) DEFAULT 0,
  conversion_increase DECIMAL(8,4) DEFAULT 0,
  roas_improvement DECIMAL(6,4) DEFAULT 0,
  click_increase DECIMAL(8,4) DEFAULT 0,
  ctr_improvement DECIMAL(6,4) DEFAULT 0,
  quality_score_improvement DECIMAL(4,2) DEFAULT 0,
  execution_time_ms INTEGER DEFAULT 0,
  success_rate DECIMAL(4,2) DEFAULT 0, -- Percentage of successful optimizations
  confidence_score DECIMAL(3,2) DEFAULT 0, -- Algorithm confidence in changes
  rollback_rate DECIMAL(4,2) DEFAULT 0, -- Percentage of changes that were rolled back
  
  UNIQUE(tenant_id, automation_type, automation_id, metric_date)
);

-- Automation Alerts Table
-- Store alerts generated by automation systems
CREATE TABLE IF NOT EXISTS automation_alerts (
  id SERIAL PRIMARY KEY,
  tenant_id VARCHAR(100) NOT NULL,
  alert_type VARCHAR(30) NOT NULL, -- 'performance_drop', 'budget_exceeded', 'optimization_failed', etc.
  severity VARCHAR(10) NOT NULL, -- 'low', 'medium', 'high', 'critical'
  title VARCHAR(200) NOT NULL,
  message TEXT NOT NULL,
  automation_context JSONB DEFAULT '{}', -- Related automation rules, campaigns, etc.
  recommended_actions JSONB DEFAULT '{}', -- Suggested fixes or optimizations
  is_resolved BOOLEAN DEFAULT false,
  resolved_at TIMESTAMP WITH TIME ZONE,
  resolved_by VARCHAR(100), -- User ID or 'system'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  INDEX (tenant_id, created_at),
  INDEX (tenant_id, is_resolved, created_at),
  INDEX (severity, created_at)
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_automation_rules_tenant_active ON automation_rules(tenant_id, is_active);
CREATE INDEX IF NOT EXISTS idx_automation_rules_type ON automation_rules(automation_type);
CREATE INDEX IF NOT EXISTS idx_automation_rules_priority ON automation_rules(priority DESC);
CREATE INDEX IF NOT EXISTS idx_automation_rules_last_executed ON automation_rules(last_executed_at);

CREATE INDEX IF NOT EXISTS idx_custom_bid_strategies_tenant_active ON custom_bid_strategies(tenant_id, is_active);
CREATE INDEX IF NOT EXISTS idx_custom_bid_strategies_usage ON custom_bid_strategies(usage_count DESC);
CREATE INDEX IF NOT EXISTS idx_custom_bid_strategies_performance ON custom_bid_strategies USING gin(average_performance);

CREATE INDEX IF NOT EXISTS idx_automation_execution_logs_tenant_date ON automation_execution_logs(tenant_id, executed_at DESC);
CREATE INDEX IF NOT EXISTS idx_automation_execution_logs_type_status ON automation_execution_logs(automation_type, execution_status);
CREATE INDEX IF NOT EXISTS idx_automation_execution_logs_metadata ON automation_execution_logs USING gin(metadata);

CREATE INDEX IF NOT EXISTS idx_bid_adjustment_history_tenant_campaign ON bid_adjustment_history(tenant_id, campaign_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bid_adjustment_history_rule ON bid_adjustment_history(automation_rule_id);
CREATE INDEX IF NOT EXISTS idx_bid_adjustment_history_strategy ON bid_adjustment_history(bid_strategy_id);

CREATE INDEX IF NOT EXISTS idx_automation_performance_metrics_tenant_date ON automation_performance_metrics(tenant_id, metric_date DESC);
CREATE INDEX IF NOT EXISTS idx_automation_performance_metrics_type ON automation_performance_metrics(automation_type, metric_date DESC);

-- Enable Row Level Security (RLS) for tenant isolation
ALTER TABLE automation_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE custom_bid_strategies ENABLE ROW LEVEL SECURITY;
ALTER TABLE automation_execution_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE bid_adjustment_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE automation_performance_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE automation_alerts ENABLE ROW LEVEL SECURITY;

-- RLS Policies for tenant isolation

-- Automation Rules Policy
CREATE POLICY automation_rules_policy ON automation_rules
  FOR ALL 
  USING (tenant_id = current_setting('app.current_tenant_id', true));

-- Custom Bid Strategies Policy
CREATE POLICY custom_bid_strategies_policy ON custom_bid_strategies
  FOR ALL 
  USING (tenant_id = current_setting('app.current_tenant_id', true));

-- Automation Execution Logs Policy
CREATE POLICY automation_execution_logs_policy ON automation_execution_logs
  FOR ALL 
  USING (tenant_id = current_setting('app.current_tenant_id', true));

-- Bid Adjustment History Policy
CREATE POLICY bid_adjustment_history_policy ON bid_adjustment_history
  FOR ALL 
  USING (tenant_id = current_setting('app.current_tenant_id', true));

-- Automation Performance Metrics Policy
CREATE POLICY automation_performance_metrics_policy ON automation_performance_metrics
  FOR ALL 
  USING (tenant_id = current_setting('app.current_tenant_id', true));

-- Automation Alerts Policy
CREATE POLICY automation_alerts_policy ON automation_alerts
  FOR ALL 
  USING (tenant_id = current_setting('app.current_tenant_id', true));

-- Add updated_at triggers
CREATE TRIGGER update_automation_rules_updated_at 
  BEFORE UPDATE ON automation_rules 
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_custom_bid_strategies_updated_at 
  BEFORE UPDATE ON custom_bid_strategies 
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Insert default automation rule templates
INSERT INTO automation_rules (
  tenant_id, 
  rule_name, 
  automation_type, 
  rule_config, 
  trigger_conditions, 
  action_config,
  is_active,
  priority
) VALUES 
(
  'system_template',
  'High-Performance Bid Optimizer',
  'bid_optimization',
  '{
    "automationType": "bid_optimization",
    "version": "1.0",
    "bidStrategy": "target_roas",
    "performanceTargets": {
      "roas_min": 3.0,
      "roas_target": 5.0,
      "cpa_max": 75.0
    },
    "adjustmentLimits": {
      "maxIncrease": 0.5,
      "maxDecrease": 0.3
    },
    "evaluationFrequency": "daily"
  }',
  '{
    "performance_criteria": {
      "min_conversions": 5,
      "min_clicks": 50,
      "evaluation_period_days": 7
    },
    "trigger_thresholds": {
      "roas_below": 3.0,
      "cpa_above": 75.0,
      "ctr_below": 0.02
    }
  }',
  '{
    "optimization_actions": [
      "adjust_keyword_bids",
      "modify_ad_group_bids",
      "update_campaign_budgets"
    ],
    "bid_strategy": "target_roas",
    "target_roas": 4.5,
    "max_bid_increase": 50,
    "max_bid_decrease": 30
  }',
  false,
  1
),
(
  'system_template',
  'Budget Reallocation Engine',
  'budget_allocation',
  '{
    "automationType": "budget_allocation",
    "version": "1.0",
    "allocationStrategy": "performance_weighted",
    "reallocationThreshold": 0.25,
    "minBudgetPercentage": 0.10,
    "maxBudgetPercentage": 0.40
  }',
  '{
    "reallocation_triggers": {
      "performance_variance": 0.25,
      "underperforming_campaigns": 2,
      "budget_utilization_below": 0.8
    },
    "evaluation_criteria": {
      "min_spend": 100.0,
      "min_conversions": 3,
      "lookback_days": 14
    }
  }',
  '{
    "reallocation_rules": {
      "high_performers_increase": 0.20,
      "low_performers_decrease": 0.15,
      "emergency_budget_threshold": 0.05
    },
    "approval_required": false,
    "notification_enabled": true
  }',
  false,
  2
),
(
  'system_template',
  'Smart Keyword Expander',
  'keyword_expansion',
  '{
    "automationType": "keyword_expansion",
    "version": "1.0",
    "expansionStrategy": "performance_based",
    "performanceCriteria": {
      "minCtr": 0.03,
      "minConversions": 2,
      "minRoas": 2.5
    },
    "maxNewKeywords": 25,
    "matchTypes": ["exact", "phrase"]
  }',
  '{
    "expansion_triggers": {
      "high_performing_keywords": 3,
      "search_volume_threshold": 500,
      "competition_level": "medium"
    },
    "quality_filters": {
      "relevance_score_min": 0.7,
      "commercial_intent_min": 0.6
    }
  }',
  '{
    "keyword_discovery": {
      "use_search_terms_report": true,
      "use_keyword_planner": true,
      "use_competitor_analysis": false
    },
    "bid_strategy": "inherit_from_source",
    "landing_page_mapping": "auto_detect"
  }',
  false,
  3
);

-- Insert default custom bid strategy templates
INSERT INTO custom_bid_strategies (
  tenant_id,
  strategy_name,
  strategy_description,
  algorithm_config,
  performance_targets,
  constraints,
  is_active
) VALUES
(
  'system_template',
  'Profit-Maximizing ROAS',
  'Advanced ROAS optimization considering profit margins and customer lifetime value',
  '{
    "algorithm_type": "profit_maximizing_roas",
    "version": "2.0",
    "optimization_objective": "maximize_profit",
    "learning_rate": 0.1,
    "confidence_threshold": 0.8,
    "adjustment_frequency": "daily",
    "model_parameters": {
      "ltv_multiplier": 1.8,
      "margin_consideration": true,
      "seasonality_adjustment": true,
      "competitor_intelligence": false
    }
  }',
  '{
    "target_roas": 4.5,
    "target_profit_margin": 0.35,
    "max_cpa": 80.0,
    "min_conversion_rate": 0.02,
    "target_ltv": 150.0
  }',
  '{
    "max_bid_increase": 0.75,
    "max_bid_decrease": 0.40,
    "min_daily_budget": 50.0,
    "max_daily_budget": 1000.0,
    "bid_floor": 0.25,
    "bid_ceiling": 25.0,
    "pause_on_poor_performance": true
  }',
  false
),
(
  'system_template', 
  'Volume-Focused Growth',
  'Optimized for maximum conversion volume while maintaining acceptable CPA',
  '{
    "algorithm_type": "volume_focused_growth",
    "version": "1.5",
    "optimization_objective": "maximize_conversions",
    "bid_aggressiveness": "moderate",
    "volume_priority": 0.8,
    "quality_priority": 0.6,
    "model_parameters": {
      "traffic_expansion": true,
      "audience_broadening": true,
      "keyword_expansion_rate": 0.15
    }
  }',
  '{
    "max_acceptable_cpa": 100.0,
    "min_daily_conversions": 10,
    "target_impression_share": 0.75,
    "conversion_volume_target": 300
  }',
  '{
    "max_bid_increase": 1.0,
    "max_bid_decrease": 0.25,
    "aggressive_scaling_enabled": true,
    "budget_flexibility": 0.3,
    "pause_threshold_cpa": 150.0
  }',
  false
),
(
  'system_template',
  'Brand Protection & Efficiency',
  'Conservative bidding strategy focused on brand protection and cost efficiency',
  '{
    "algorithm_type": "brand_protection_efficiency",
    "version": "1.0",
    "optimization_objective": "minimize_cost",
    "brand_protection_level": "high",
    "efficiency_focus": "cost_per_acquisition",
    "model_parameters": {
      "brand_keyword_priority": 0.9,
      "competitor_protection": true,
      "quality_score_emphasis": 0.8
    }
  }',
  '{
    "max_cpa": 50.0,
    "min_impression_share_brand": 0.85,
    "target_quality_score": 8.0,
    "max_cost_per_click": 5.0
  }',
  '{
    "max_bid_increase": 0.25,
    "max_bid_decrease": 0.5,
    "conservative_scaling": true,
    "brand_keyword_bid_floor": 1.0,
    "generic_keyword_bid_ceiling": 3.0
  }',
  false
);

-- Create automation performance tracking functions

-- Function to calculate automation ROI
CREATE OR REPLACE FUNCTION calculate_automation_roi(
  tenant_id_param TEXT,
  automation_type_param TEXT,
  start_date DATE,
  end_date DATE
) RETURNS TABLE (
  automation_type TEXT,
  total_cost_savings DECIMAL,
  total_conversion_increase DECIMAL,
  total_roas_improvement DECIMAL,
  roi_percentage DECIMAL,
  confidence_score DECIMAL
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    apm.automation_type,
    SUM(apm.cost_savings) as total_cost_savings,
    SUM(apm.conversion_increase) as total_conversion_increase,
    AVG(apm.roas_improvement) as total_roas_improvement,
    (SUM(apm.cost_savings) / NULLIF(SUM(apm.cost_savings) * 0.1, 0)) * 100 as roi_percentage,
    AVG(apm.confidence_score) as confidence_score
  FROM automation_performance_metrics apm
  WHERE apm.tenant_id = tenant_id_param
    AND (automation_type_param IS NULL OR apm.automation_type = automation_type_param)
    AND apm.metric_date BETWEEN start_date AND end_date
  GROUP BY apm.automation_type;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to get automation health status
CREATE OR REPLACE FUNCTION get_automation_health_status(tenant_id_param TEXT)
RETURNS TABLE (
  total_active_rules INTEGER,
  total_executions_last_7d INTEGER,
  average_success_rate DECIMAL,
  total_cost_savings_last_30d DECIMAL,
  performance_grade CHAR(1)
) AS $$
DECLARE
  health_grade CHAR(1);
  success_rate DECIMAL;
  cost_savings DECIMAL;
BEGIN
  -- Get basic stats
  SELECT 
    COUNT(*) FILTER (WHERE is_active = true),
    COUNT(*) FILTER (WHERE last_executed_at >= NOW() - INTERVAL '7 days'),
    AVG(COALESCE((metadata->>'success_rate')::DECIMAL, 0))
  INTO total_active_rules, total_executions_last_7d, success_rate
  FROM automation_rules ar
  LEFT JOIN automation_execution_logs ael ON ar.id::TEXT = ael.automation_id
  WHERE ar.tenant_id = tenant_id_param;
  
  -- Get cost savings
  SELECT COALESCE(SUM(cost_savings), 0)
  INTO cost_savings
  FROM automation_performance_metrics
  WHERE tenant_id = tenant_id_param 
    AND metric_date >= CURRENT_DATE - INTERVAL '30 days';
  
  -- Calculate health grade
  IF success_rate >= 0.9 AND cost_savings >= 500 THEN
    health_grade := 'A';
  ELSIF success_rate >= 0.8 AND cost_savings >= 250 THEN
    health_grade := 'B';
  ELSIF success_rate >= 0.7 AND cost_savings >= 100 THEN
    health_grade := 'C';
  ELSIF success_rate >= 0.5 THEN
    health_grade := 'D';
  ELSE
    health_grade := 'F';
  END IF;
  
  RETURN QUERY SELECT 
    total_active_rules,
    total_executions_last_7d,
    success_rate as average_success_rate,
    cost_savings as total_cost_savings_last_30d,
    health_grade as performance_grade;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Update migration record
INSERT INTO tenant_configs (tenant_id, config_key, config_value) 
VALUES ('migration', 'schema_version', json_build_object('version', '004', 'created_at', NOW()))
ON CONFLICT (tenant_id, config_key) 
DO UPDATE SET 
  config_value = EXCLUDED.config_value,
  updated_at = NOW();

-- Add comments for documentation
COMMENT ON TABLE automation_rules IS 'Enterprise-tier custom automation rules and configurations';
COMMENT ON TABLE custom_bid_strategies IS 'Enterprise-tier custom bidding algorithms and strategies';
COMMENT ON TABLE automation_execution_logs IS 'Audit trail for all automation executions and results';
COMMENT ON TABLE bid_adjustment_history IS 'Historical record of all automated bid changes for audit and rollback';
COMMENT ON TABLE automation_performance_metrics IS 'Performance tracking for automation effectiveness';
COMMENT ON TABLE automation_alerts IS 'System-generated alerts from automation processes';

-- Create function to clean up old automation logs (data retention)
CREATE OR REPLACE FUNCTION cleanup_automation_logs(retention_days INTEGER DEFAULT 90)
RETURNS INTEGER AS $$
DECLARE
  deleted_count INTEGER;
BEGIN
  DELETE FROM automation_execution_logs 
  WHERE executed_at < NOW() - (retention_days || ' days')::INTERVAL;
  
  GET DIAGNOSTICS deleted_count = ROW_COUNT;
  
  RETURN deleted_count;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Schedule cleanup job (would need to be set up in a cron job or similar)
-- SELECT cleanup_automation_logs(90); -- Keeps 90 days of logs